version: '3.8'

x-flink-common: &flink-common
  image: flink_pro:v10
  networks:
    - bigdata

x-flink-taskmanager: &flink-taskmanager
  <<: *flink-common
  volumes:
    - flink_data:/tmp/
  environment:
    - |
      FLINK_PROPERTIES=
      jobmanager.rpc.address: jobmanager
      taskmanager.numberOfTaskSlots: 3
      state.backend: filesystem
      state.checkpoints.dir: file:///tmp/flink-checkpoints
      heartbeat.interval: 1000
      heartbeat.timeout: 5000
      classloader.resolve-order: parent-first
    - AWS_ACCESS_KEY_ID=admin
    - AWS_SECRET_ACCESS_KEY=password
    - AWS_REGION=us-east-1
    - AWS_DEFAULT_REGION=us-east-1
    - S3_ENDPOINT=http://nginx:9000 
    - S3_PATH_STYLE_ACCESS=true

services:
  sql-client:
    <<: *flink-common
    hostname: sql-client
    container_name: sql-client
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - S3_ENDPOINT=http://nginx:9000
      - S3_PATH_STYLE_ACCESS=true

  jobmanager:
    <<: *flink-common
    hostname: jobmanager
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - flink_data:/tmp/
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
        rest.flamegraph.enabled: true
        classloader.resolve-order: parent-first
        web.backpressure.refresh-interval: 10000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - S3_ENDPOINT=http://nginx:9000
      - S3_PATH_STYLE_ACCESS=true
    
  taskmanager-1:
    <<: *flink-taskmanager
    hostname: taskmanager-1
    container_name: taskmanager-1
    depends_on:
      - jobmanager
    command: taskmanager

  taskmanager-2:
    <<: *flink-taskmanager
    hostname: taskmanager-2
    container_name: taskmanager-2
    depends_on:
      - jobmanager
    command: taskmanager
    
volumes:
  flink_data:

networks:
  bigdata:
    external: true